### ISSUE TITLE
Update the paper link

### ISSUE THREAD

**Issue by szhang42** [bansky-cl/Diffusion_NLP_Papers#2]
Hello, 

Thanks for having this great list of diffusion NLP papers. For the "Language RF 2024.3 NAACL 2024," could you update the paper link to this arxiv link (https://arxiv.org/abs/2403.16995)? It seems that the current link does not direct to the paper. Thanks!

**Comment by bansky-cl** [comment]
Thank you for your kind reminder. 

I noticed that the paper had been renamed in the last update. So I plan to refer to the NAACL accepted version. Currently, it has been modified to the preprint version. 

Here I would also like to congratulate you on the acceptance of your paper.

**Comment by szhang42** [comment]
Thanks!
